X16 Reference - 04 - KERNAL.md
Based on:
- https://sta.c64.org/cbm64krnfunc.html
- https://www.pagetable.com/c64ref/kernal/
=> Update registers affected / used rows

Commander X16 Programmer's Reference Guide.md, X16 Reference - 11 - Working with CMDR-DOS.md
Just some things I noticed after the initial PR
=> [CMDR-DOS] minor changes, added to TOC

X16 Reference - 03 - BASIC.md
Somehow I missed pushing this one edit.
=> [BASIC] additional minor rewording

X16 Reference - 07 - Memory Map.md
=> Update X16 Reference - 07 - Memory Map.md

X16 Reference - 02 - Editor.md, X16 Reference - 03 - BASIC.md, X16 Reference - 09 - Sound Programming.md, X16 Reference - 10 - IO Programming.md
=> [PRG] document recent changes to the ROM

X16 Reference - 08 - Video Programming.md
Minor tweak to make chart a bit more clear and useful
=> improve video memory layout chart

X16 Reference - 03 - BASIC.md
Doc update for https://github.com/X16Community/x16-rom/pull/83
=> [PRG] BASIC: add REN command

commander-x16-wikipedia-entry.txt
based off the Commander X16 Videos by David "8-Bit Guy" Guy...
=> updated wiki draft based off new information

X16 Reference - 04 - KERNAL.md
https://github.com/X16Community/x16-rom/pull/90 removed this limitation
=> [PRG] Doc update for https://github.com/X16Community/x16-rom/pull/90

X16 Reference - 03 - BASIC.md
Doc update for https://github.com/X16Community/x16-rom/pull/91
=> [PRG] new BASIC functions POINTER and STRPTR

.github/workflows/build.yml, VERA Programmer's Reference.md
includes a minor change to the VERA doc's markdown to make pandoc happier.
=> [CI/CD] add VERA Programmer's Reference PDF conversion to CI

X16 Reference - 03 - BASIC.md
doc update for https://github.com/X16Community/x16-rom/pull/94
=> [PRG] new RPT$ BASIC function

X16 Reference - 05 - Math Library.md
The code example that I've added works with 64tass and assembles without error with ca65 however I can't get a runnable program out of the latter. I assume the code works correctly for ca65 too, maybe someone can verify this. *edit* managed to get it to run correctly.
=> Mathlib usage howto and cleanup

X16 Reference - 02 - Editor.md
=> [PRG] add missing bold on pgup/pgdn

VERA Programmer's Reference.md
This change documents  https://github.com/X16Community/x16-emulator/pull/159
=> VERA: fifo loop

X16 Reference - 06 - Machine Language Monitor.md
This is a companion update to https://github.com/X16Community/x16-rom/pull/173
=> [PRG] Document new MONITOR behaviors

X16 Reference - 03 - BASIC.md, X16 Reference - 04 - KERNAL.md
=> [PRG] flesh out LOAD kernal docs and BLOAD basic docs

X16 Reference - 03 - BASIC.md, X16 Reference - 07 - Memory Map.md
=> [PRG] remove mention of GEOS command

X16 Reference - 04 - KERNAL.md
Documents https://github.com/X16Community/x16-rom/pull/175
=> fix: document use of r3H by RTC calls for the day of the week

VERA FX Reference.md, X16 Reference - 07 - Memory Map.md, X16 Reference - 09 - Sound Programming.md
The story is pretty simple - place an X16 pre-order, went to read the docs and came across a few typos. This PR fixes them.
=> Fix a few typos

X16 Reference - 04 - KERNAL.md
This PR includes a note that explains what to do when using the LZSA library to compress data, and explains the command  for doing it via CLI in the process.
=> Include docs for compressing using LZSA library

X16 Reference - 03 - BASIC.md
Saw this was missing, so I added a simple entry.
=> Document `CLOSE` command

X16 Reference - 05 - Math Library.md
PR for rom to implement it is here https://github.com/X16Community/x16-rom/pull/231
Setting this PR as draft until above gets approved.
=> document the VAL_1 routine that got implemented

X16 Reference - Appendix C - 65C02 Processor.md
Add information about STP when using the emulator and debugger
=> Update X16 Reference - Appendix C - 65C02 Processor.md

X16 Reference - 03 - BASIC.md
We wrote a whole section at the top of the BASIC guide, but someone asked again today how to overwrite an existing program.
=> Document SAVE command, since @: keeps coming up 

X16 Reference - 03 - BASIC.md
Documented the LIST command, including the pause with space bar functionality.
=> Documented LIST command

X16 Reference - 04 - BASIC.md
Documentation for the two new functions TDATA & TATTR
=> Added TDATA & TATTR functions to documentation

X16 Reference - 13 - Working with CMDR-DOS.md
Docs for https://github.com/X16Community/x16-rom/pull/306
=> CMDR-DOS: fast serial command implementation

X16 Reference - 05 - KERNAL.md
Additionally documents https://github.com/X16Community/x16-rom/pull/303
=> KERNAL: extapi, additional docs

README.md, X16 Reference - Appendix F - 65C816 Processor.md
Initial draft of the 65C816 docs.
=> Create 65816 docs

X16 Reference - 05 - KERNAL.md
Fixed comments in example (just tested this in my code, and comments are now consistent with behavior)
=> minor edit system reset example

X16 Reference - Appendix C - 65C02 Processor.md
I have been using this 65C02 reference documentation often recently, so I have made a pass improving a few minor issues and omissions I noticed.
=> fixed some minor issues, added additional info, improved consistency

X16 Reference - 13 - Working with CMDR-DOS.md
Docs for https://github.com/X16Community/x16-rom/pull/334
=> DOS: document Tell command

X16 Reference - 05 - KERNAL.md
Fixes an incorrect register value for the console_put_image KERNAL call.
=> console_put_image Register Fix

X16 Reference - 05 - KERNAL.md
This commit adds the description block for the CHROUT/BSOUT routine under the KERNAL chapter. Additionally, the description contains the caveat that CHROUT should not be called from within an interrupt handler, due to the routine ending with a CLI statement (which can cause issues for non-reentrant handler routines).
Closes #151.
=> Add the description for KERNAL's CHROUT

X16 Reference - 12 - IO Programming.md, X16 Reference - 14 - Hardware.md
Documenting contents of KERNAL NVRAM, as I did not find this information documented elsewhere.
Information source:
x16-rom, rtc.s and screen.s
=> Document contents of KERNAL NVRAM (IO programming), and update hardware pinout

X16 Reference - 02 - Getting Started.md
Just fixes a couple of typos I spotted while reading
=> Update X16 Reference - 02 - Getting Started.md

X16 Reference - 05 - KERNAL.md
see https://cx16forum.com/forum/viewtopic.php?p=34939#p34939
=> mode 128 is 320x240

README.md, X16 Reference - Appendix G - Onboard Upgrade Guide.md, X16 Reference - Appendix H - Onboard Upgrade Guide.md
This will be rewritten to markdown. Just pushing what I have now in the meantime.
=> Add complete update guide

X16 Reference - Appendix H - Onboard Upgrade Guide.md
Simplify upgrade guide. Update SMC and add prerelease VERA.
=> Refresh onboard upgrade guide

X16 Reference - 12 - IO Programming.md
=> PRG 12: correct incorrect IRQ/NMI information re VIA1/VIA2

X16 Reference - 05 - KERNAL.md
This documents the recently added (published for user programs) `memory_decompress_from_func` subroutine.
Related to X16Community/x16-rom#380
=> Document `memory_decompress_from_func`

X16 Reference - 09 - VERA Programmer's Reference.md
=> Document VERA SPI control bit "Auto-TX"

X16 Reference - 13 - Working with CMDR-DOS.md
=> fix: string index of position field

X16 Reference - 03 - Editor.md, X16 Reference - 05 - KERNAL.md
please disregard my terrible commit names.
=> minor newline fixes in 05 - KERNAL and change of wording in 03 - EDITOR

X16 Reference - 05 - KERNAL.md
See https://github.com/X16Community/x16-rom/pull/395
=> Document default_palette
