X16Community/x16-docs

- VERA Programmer's Reference.md
The first 16 colors in the current default palette aren't very well tuned to what the VIC-II actually outputs.
So I think rewording this is appropriate.
I'm no expert on this but here's a pretty thorough analysis and a better RGB representation of the C64 (VIC-II) palette https://www.pepto.de/projects/colorvic/
> more accurate description of the first 16 palette colors

- X16 Reference - 11 -  Working with CMDR-DOS.md
Added new chapter to the guide. Also added some instructions on how to use the DOS commands. 
While the primary intent was to get the DOS commands into the main documentation repo, it wasn't entirely clear how to use some of the commands, like Position (which we spent a lot of time discussing on the forum) and how to use the Directory options (this still needs more expansion.)
> Create X16 Reference - 11 -  Working with CMDR-DOS.md

- X16 Reference - 03 - BASIC.md
This corrects the addresses used by the SYS command to preload and unload the .A, .X, .Y, and Status registers.
> Fix SYS documentation

- X16 Reference - 04 - KERNAL.md
This was bothering me. My eyeballs didn't see any other line break-related issues.
> Fix missing Markdown line break

- X16 Reference - 05 - Math Library.md
$FE87     FLOAT     FAC = (u8).A    
This is wrong,  it loads the FAC with the _signed_ byte in A, not unsigned.
The implementation confirms this, it falls through in to FLOATS  which loads a signed word into FAC.
https://github.com/X16Community/x16-rom/blob/r42/math/code20.s#L120
(I had to change prog8 to use GIVAYF instead to get correct results from ubyte -> float conversion)
> FLOAT takes signed byte, not unsigned

- VERA Programmer's Reference.md
- X16 Reference - 04 - KERNAL.md
Relates to https://github.com/X16Community/x16-rom/pull/72 and a release posted at https://github.com/X16Community/vera-module/releases/tag/v0.1.1, yet to be PRed to upstream vera-module.
> [PRG/VERA] update docs for ROM changes and VERA additions

- X16 Reference - 04 - KERNAL.md
In a response to a user on the forum that (rightfully) complained about the C64 routines having zero documentation.
> mention link to C64 kernal routines reference page (external)

- X16 Reference - 05 - Math Library.md
It's been mentioned on the forums and on Reddit that this documentation isn't helpful enough. I started by moving the reference to the C128  Developer Pack to the top of the file to make it more clear that there's other documentation out there.
Related threads:
https://cx16forum.com/forum/viewtopic.php?p=27611#p27611
https://www.reddit.com/r/CommanderX16/comments/11kb62i/trying_to_subtract_with_the_kernel/
> moved C128 reference to top

- X16 Reference - 02 - Editor.md
It doesn't look like `$08` means backspace anywhere in the X16 editor PETSCII/keyboard handling code, so that meaning has been removed from this table.
Closes #48
> [PRG] clarify new PETSCII table

- X16 Reference - 02 - Editor.md
This is a KERNAL feature that the machine language monitor uses, but it is useful for user programs as well.
> [PRG] document edkeyvec

- X16 Reference - 10 - IO Programming.md
Updates information about the SMC.
- Added that it handles PS/2 keyboard and mouse to the general description.
- Added missing commands/offset to the table
> Update info about the SMC

- X16 Reference - 07 - Memory Map.md
- X16 Reference - 12 - Hardware.md
Update based on below plus some Discord convos. 
TLDR:
Documentation change to suggest cartridges which require MMIO use IO7 first and expansion cards start with IO5 first (5-7 as those are the 2MHz ranges since there are only 2 8MHz ranges).
> Clarify cartridge MMIO usage

- X16 Reference - 04 - KERNAL.md
The note of "but is always greater than 0" is based on an assumption. Is this correct?
Should that detail perhaps not be mentioned at all.
> mention the fact that MACPTR and MCIOUT can return less than the requested number of bytes

- X16 Reference - 07 - Memory Map.md
The docs contained an outdated reference to CBDOS, which is now called CMDR-DOS. This pull request updates the text to contain the new name.
> Update reference of CBDOS to new name CMDR-DOS

- VERA Programmer's Reference.md
This change documents the way 2bpp and 4bpp pack pixels, so that it's not ambiguous whether they're packed or not and how they're packed.
> Include documentation for 2bpp and 4bpp pixel packing

- X16 Reference - 03 - BASIC.md
Saw where someone had probably copied the entry for MON to create the documentation for MENU and overlooked an instance of MON in the body of the entry.
> Update X16 Reference - 03 - BASIC.md - changed MON to MENU

- X16 Reference - 07 - Memory Map.md
- X16 Reference - 13 - Working with CMDR-DOS.md
This documents the parameter area at $0:BF00, plus the DOS Wedge commands. 
(Yes, these were two separate PRs, but the merge conflict made me start over.)
> document $0:BF00 block and DOS wedge

- X16 Reference - Appendix C - 65C02 Processor.md
Some minor spelling issues
Added INC, DEC instructions
Replaced "opcode" with "instruction" when referring to the written form. Left "opcode" when referring to the numeric form Fixed BNE description
As noted in conversation with m00dawg and MooingLemur:
"Instruction" is the written form, ie: LDA $1234
"opcode" is preferred for the numeric form, ie: $AD
I'm pretty sure more edits will be needed. I have not confirmed all Rockwell instructions are in the list, and I'd like to add an opcode matrix, since the opcodes and brief flag listings are not included in the main body. (If writing an assembler or compiler, having this is important.)
> Update X16 Reference - Appendix C - 65C02 Processor.md

- X16 Reference - Appendix C - 65C02 Processor.md
This version of the 65C02 docs comes from a CSV file, run through a script, to create the documentation. 
I still need to do an opcode-by-opcode comparison with the WDC data sheet to confirm timings (especially page-crossing +1), but this version gives all the important stuff, including address modes, opcode numbers, and a description of each instruction.
> Import 65C02 docs from merge script

- .github/workflows/build.yml
- X16 Reference - 08 - Memory Map.md
- X16 Reference - Appendix C - 65C02 Processor.md
BASLOAD wasn't in the memory map
updated page breaks in 65C02
updated actions versions that were causing deprecation warnings.
Closes #142
> Update memory map, add page break in 65C02, update actions versions

- X16 Reference - Appendix C - 65C02 Processor.md
This fixes the description for the rotate/shift instructions. The original descriptions were incorrect.
> fix ROL, ROR, ASL, LSR errors

- X16 Reference - Appendix C - 65C02 Processor.md
simple change to the BRK description
> BRK uses the IRQ vector, not NMI

- X16 Reference - 09 - VERA Programmer's Reference.md
It seems this was changed back when memory layout was moved into VERA Programmers Reference
> Fixed unused size at $1:F800-$1F9BF

- X16 Reference - 05 - KERNAL.md
Just a quick example of reserving space for machine language routines in BASIC memory.
> Update X16 Reference - 05 - KERNAL.md

- X16 Reference - 12 - IO Programming.md
Power LED brightness control has been removed from the SMC and isn't possible with current hardware, but is still documented. This PR removes those remnants.
> SMC: Stop referencing Power LED brightness control that doesn't exist anymore

- X16 Reference - 12 - IO Programming.md
The activity LED is not actually connected to a pin on the SMC that is able to do PWM output.
> Change description of activity LED function to only on/off

- X16 Reference - Appendix C - 65C02 Processor.md
Used this one-liner to do this rewrite
`perl -pe 's/ ([C-])([Z-])([I-])([D-])([B-])([V-])([N-]) / $7${6}-$5$4$3$2$1 /g' < in.md > out.md`
Closes #159
> Appendix C: flip flags around to conventional display

- X16 Reference - 14 - Hardware.md
New version is what the silkscreen on the board says, and it matches what my multimeter says.
Or at least, the 5VSB pin is the same pin powering the microcontroller, it doesn't appear to be a dead short to +5VSB on the ATX header, so something odd seems to be going on.
> Update I2C/SMC header to match Dev Edition Rel 1.0

- X16 Reference - 05 - KERNAL.md
Also replace $FEAB with a label in the example.
> extapi: Fix PFKEY example referring to the wrong KERNAL address

- X16 Reference - 06 - Math Library.md
- Rename FAC to FACC for consistency.
- Change the format to formulas to be consistent with the rest of the documentation
as well as the C128 documentation.
- Add `PACK` / `UNPACK` wherever necessary.
- Fix `MOVAF` not documenting that it is rounding `FACC`.
- Fix `MOVEF` being misdocumented; it is not equivalent to `MOVAF` since it doesn't
round.
> [MATH] Fix and improve the movement function documentation

- X16 Reference - 05 - KERNAL.md
Clearly document the X16 KERNAL `RDTIM` function, so there's less chance others will refer to incorrect C64 documentation.
Kernal routine `RDTIM` returns the low-order byte in A, the mid-order in X, and the high-order in Y (i.e., A changes fastest, Y slowest).  The [Kernal docs](https://github.com/X16Community/x16-docs/blob/master/X16%20Reference%20-%2005%20-%20KERNAL.md#kernal-api-functions) only refer to the C64 function.  My copy of the _Commodore 64 Programmer's Reference Guide_ says "the accumulator contains the most significant byte".  Several of the descriptions on the comparative reference https://www.pagetable.com/c64ref/kernal/#RDTIM contradict one another on this point.
[I first asked about this in a Discord discussion](https://discord.com/channels/547559626024157184/54924808937 …
> document RDTIM KERNAL function

- X16 Reference - 05 - KERNAL.md
This update to the KERNAL docs resolves a range error for the "weekday" value listed under the entry for `clock_set_date_time`; the range was updated from 0-6 to 1-7, per actual RTC functionality.
Closes #119
> Update the RTC Weekday value range

- X16 Reference - 05 - KERNAL.md
this allows people to actually put an upper bound to the size of the buffer to use.
> mention that MACPTR with size 0 reads up to a maxium of 512 bytes

- X16 Reference - 09 - VERA Programmer's Reference.md
> Changes meant for PR #213

- X16 Reference - 08 - Memory Map.md
Quote from Discord by @mooinglemur:
"CBDOS is the old name, it was renamed to CMDR-DOS".
https://discord.com/channels/547559626024157184/549248089379307522/1285256940909363200
> Rename bank CBDOS to CMDRDOS

- .github/workflows/build.yml
- README.md
- X16 Reference - Appendix G - ZSM File Format.md
Taken from https://github.com/tildearrow/furnace/blob/master/papers/zsm-format.md
Folks needing to parse or generate ZSM files or that just need to know the file format for details on the X16 should ideally be able to get the information from one place.
> Adding ZSM file format

- X16 Reference - 09 - VERA Programmer's Reference.md
This PR improves readability by movingthe rows for all DCSEL-affected registers into collapsible regions using the `<details>` HTML tag. They still need to be open by default to allow users to search through their contents, but users can now collapse the entries for those DCSEL values they don't care about.
> VERA: Split register documentation for $9F29-$9F2C into separate tables within collapsible regions for each DCSEL value

- X16 Reference - Appendix G - ZSM File Format.md
Updated to reflect what ZSMKit currently supports.
> Appendix G: update ZSM specification to include chip ID allocations for MIDI, additional clarifications

- X16 Reference - Appendix A - Sound.md
- X16 Reference - Appendix C - 65C02 Processor.md
- X16 Reference - Appendix D - Official Expansion Cards.md
- X16 Reference - Appendix E - Diagnostic Bank.md
- X16 Reference - Appendix F - 65C816 Processor.md
- X16 Reference - Appendix G - ZSM File Format.md
- X16 Reference - Appendix H - Onboard Upgrade Guide.md
Some typo fixes in the appendices. I've tried to avoid subjective changes such as use of hyphenation. Given the technical nature of opcodes and whatnot, which I'm not an expert on, I suggest checking that it makes sense.
> Appendix typos

- X16 Reference - 03 - Editor.md
Docs still reference the old japanese layout. This PR changes that, so it points to the layout, that's going to be in future releases. Pre-r49 version of the layout is so useless it's probably not worth mentioning it in the revised documentation (and the new link does mention the behaviour of the old layout anyway).
> Editor: Mention Updated Japanese keyboard layout

- X16 Reference - 05 - KERNAL.md
Improve description regarding CRC:
- Describe more accurately which CRC configuration is used (CRC-16/IBM-3740)
- Add link to an online CRC calculator using the same CRC configuration
- Describe the bug in previous Kernal versions ([#381](https://github.com/X16Community/x16-rom/issues/381)), and when to expect different CRC based on Kernal version
@mooinglemur
> Add more details to the CRC kernal function

- X16 Reference - Appendix H - Onboard Upgrade Guide.md
Update the upgrade guide:
- Mention 48.0.1 as latest VERA release
- List stock version numbers for boards newer than PR01000
@mooinglemur
> Update upgrade guide

- X16 Reference - 04 - BASIC.md
- X16 Reference - 05 - KERNAL.md
- X16 Reference - 13 - Working with CMDR-DOS.md
Add warnings regarding appending to file
- CMDR-DOS: Describe the problem ([#369](https://github.com/X16Community/x16-rom/pull/369))
- Kernal: Add warning for function SETNAM (referring to CMDR-DOS)
- Basic: Add warning for function BSAVE (referring to CMDR-DOS)
@mooinglemur 
@Fulgen301 FYI, you had some opinions on this one
> Add warning regarding appending to file

- X16 Reference - Appendix F - 65C816 Processor.md
The description of the Emulation mode flag had the meanings the wrong way around.  Fix this.
[1] W65C816S Datasheet
https://www.westerndesigncenter.com/wdc/documentation/w65c816s.pdf
"2.8 Processor Status Register (P)
... illustrates the features of the Native (E=0) and Emulation (E=1)
modes.
...
Table 2-1 W65C816S Microprocessor Programming Model
...
Emulation
1=W65C02 Emulation Mode
0=Native Mode
"
> Fix 65C816 Emulation mode flag description

- X16 Reference - 03 - Editor.md
- X16 Reference - 04 - BASIC.md
- X16 Reference - 05 - KERNAL.md
- X16 Reference - 06 - Math Library.md
- X16 Reference - 08 - Memory Map.md
- X16 Reference - 09 - VERA Programmer's Reference.md
- X16 Reference - 10 - VERA FX Reference.md
- X16 Reference - 11 - Sound Programming.md
- X16 Reference - 12 - IO Programming.md
- X16 Reference - 14 - Hardware.md
- X16 Reference - Appendix E - Diagnostic Bank.md
- X16 Reference - Appendix F - 65C816 Processor.md
In IntelliJ IDEA, the preview can get quite difficult to read due to non-maths things getting interpreted as math notation. This isn't an issue in Obsidian, VS Code or GitHub's own preview, despite all of those supporting math notation (as evidenced in the [Math Library](https://github.com/X16Community/x16-docs/blob/master/X16%20Reference%20-%2006%20-%20Math%20Library.md#how-to-use-the-routines) chapter).
|![IDEA screenshot](https://github.com/user-attachments/assets/ae18e0ec-8e1f-4e09-8c73-9ead477a7feb)|
|---|
|![IDEA screenshot](https://github.com/user-attachments/assets/3b01566d-3145-44e5-987a-28c74494132c)|
To fix this, in paragraphs that contain two or more dollar signs (excluding in `monospace`) I've escaped them. Paragraphs which contain only a single dollar sign, I've left alone. …
> Escape pairs of dollar signs

- X16 Reference - Appendix F - 65C816 Processor.md
The similarity of STP to other STx functions have likely made it an easy mistake to group it together with the other Store functions.
However STP stops the CPU until it is reset and has nothing to do with storing any values.
In this PR, I have moved STP to Interrupt, but maybe it should actually go into flow? - Inputs welcome.
> Moved STP from Store section to Interrupt section
